const CODE_SUCCESS_UPDATE = 200;
const CODE_SUCCESS_NEW = 201;
const CODE_BAD_REQUEST = 400;
const CODE_ERROR_SYSTEM = 500;
const RESPONSE_MESSAGE = {
    [CODE_SUCCESS_UPDATE] : "Successfully updated",
    [CODE_SUCCESS_NEW] : "Successfully inserted",
    [CODE_BAD_REQUEST] : "Invalid request",
    [CODE_ERROR_SYSTEM] : "Internal server error"
}

module.exports = {
    CODE_SUCCESS_UPDATE:CODE_SUCCESS_UPDATE,
    CODE_SUCCESS_NEW:CODE_SUCCESS_NEW,
    CODE_BAD_REQUEST:CODE_BAD_REQUEST,
    CODE_ERROR_SYSTEM:CODE_ERROR_SYSTEM,
    RESPONSE_MESSAGE:RESPONSE_MESSAGE
}